version: '3.5'

services:
  stream-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/config.js:/usr/src/app/config/config.js

    ports:
      - "5173:5173"

    networks:
      - stream-frontend


networks:
  stream-frontend:
    driver: bridge

