export const routes = {
    login: '/login',
    admin: '/admin/:page?/:section?',
    personal: '/admin/personal',
    upload: '/admin/upload',
    streams: '/streams',
    stream: '/stream',
    playlists: '/playlists',
    uploadedStream: 'admin/stream/uploaded',
    uploadStream: 'admin/stream/upload',
    uploadedVideo: 'admin/video/uploaded',
    uploadVideo: 'admin/video/upload',
    uploadedPlaylists: 'admin/playlists/uploaded',
    uploadPlaylists: 'admin/playlists/upload',
    playlist: ':/playlistId',
    video: ':videoId',
}