export const routes = {
    login: '/login',
    admin: '/admin',
    personal: '/admin/personal',
    upload: '/admin/upload',
    streams: '/streams',
    stream: '/stream',
    playlists: '/playlists',
    adminVideo: '/admin/video',
    adminPlaylist: '/admin/playlist',
    adminStream: '/admin/stream',
    uploadedStream: '/admin/stream/uploaded',
    uploadStream: '/admin/stream/upload',
    uploadedVideo: '/admin/video/uploaded',
    uploadVideo: '/admin/video/upload',
    uploadedPlaylists: '/dmin/playlists/uploaded',
    uploadPlaylists: '/admin/playlists/upload',
    playlist: '/:playlistId',
    video: ':videoId',
}